site_name: Nowhere Technical Guide

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - navigation.footer

plugins:
  - search
  - markdown-exec

nav:
  - Home: index.md
  - Styling:
    - No LocalScripts: styling/localscripts.md
    - Naming variables: styling/naming-variables.md
    - Requires: styling/requires.md
    - Spacing (WIP): styling/spacing.md
  - Cookbook:
    - What is a Feature?: cookbook/features.md
    - 'Feature: "Kill Brick"': cookbook/killbrick.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css
